version: "2.4"
services:
  python:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
  node:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
  ruby:
    build:
      context: .
      dockerfile: ./ruby/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
  csharp:
    build:
      context: .
      dockerfile: ./c-sharp/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:80"
  go:
    build:
      context: .
      dockerfile: ./golang/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"